name: Clang-Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Install clang-format 22
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils

          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.0-rc3/LLVM-22.1.0-rc3-Linux-X64.tar.xz > /dev/null

          sudo mkdir -p /opt/llvm-22

          tar -xf LLVM-22.1.0-rc3-Linux-X64.tar.xz -C /opt/llvm-22

          echo "/opt/llvm-22/bin" >> $GITHUB_PATH
          export PATH=/opt/llvm-22/bin:$PATH
          which clang-format
          clang-format --version

      - name: Check version
        run: |
          export PATH=/opt/llvm-22/bin:$PATH
          ls /opt/llvm-22/
          clang-format --version
          which clang-format

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run clang-format check
        run: |
          FILES=$(git ls-files '*.cxx' '*.hxx' '*.txx')

          if [ -z "$FILES" ]; then
            echo "no file to check."
            exit 0
          fi

          clang-format -i $FILES

          # If file change -> error
          if ! git diff --exit-code; then
            echo "::error::Format error."
            exit 1
          fi

          echo "Clang-format OK."